#!/bin/sh

### BEGIN INIT INFO
# Provides:             %{app_name}
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Should-Start:         $network
# Should-Stop:          $network
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    %{app_name}
# Description:          %{app_desc}
### END INIT INFO
                                
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
DAEMON=/usr/bin/twistd
NAME=%{app_name}
DESC=${NAME}
USER=root

test -x ${DAEMON} || exit 0

set -e

case "${1}" in
    start)
        echo -n "Starting ${DESC}: "

        start-stop-daemon --start --quiet --pidfile /var/run/${NAME}.pid \
            --exec ${DAEMON} --logfile=%{app_log} --rundir=%{app_share} \
            --file=%{app_file}

        echo "${NAME}."
        ;;

    stop)
        echo -n "Stopping ${DESC}: "

        start-stop-daemon --stop --quiet --pidfile /var/run/${NAME}.pid \
            --oknodo

        echo "${NAME}."
        ;;

    restart|force-reload)
        echo -n "Restarting ${DESC}: "

        start-stop-daemon --stop --quiet --pidfile /var/run/${NAME}.pid \
            --oknodo

        sleep 1

        start-stop-daemon --start --quiet --pidfile /var/run/${NAME}.pid \
            --exec ${DAEMON} --logfile=%{app_log} --rundir=%{app_share} \
            --file=%{app_file}

        echo "${NAME}."
        ;;

    *)
        N=/etc/init.d/${NAME}
        echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac
